trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Run Script to Check connection'
  inputs:
    targetType: 'inline'
    script: |
      statusCode=$(curl -X GET \
      https://integration-frzcl4bwjotr-fr.integration.ocp.oraclecloud.com/ic/home/ \
      -u anupama.rana.garg@accenture.com:Revir210$ -H "Accept: application/json" -w "%{http_code}\n" -s)
        if [ $statusCode -eq 200 ]
          then
            echo "Connection successful"
          else
            echo "Connection failed"
        fi
- task: Bash@3
  displayName: 'Run Script to post'
  inputs:
    targetType: 'inline'
    script: |
      curl -s -u sumit.kumar.singh3@gds.ey.com:Welcome@12345 -H "Accept: application/json" -X POST -F \
            "file=@"TEST_002_01.00.0000.iar";type=application/octet-stream "\
            https://oic-bmjmq3ynseyn-bo.integration.ocp.oraclecloud.com/ic/home
            
- task: Bash@3
  displayName: 'Run Script'
  inputs:
    targetType: 'inline'
    script: |
      act_status=$(curl  -X POST -u sumit.kumar.singh3@gds.ey.com:Welcome@12345 -H "Content-Type:application/json" -H \
            "X-HTTP-Method-Override:PATCH" -d @activate.json https://oic-bmjmq3ynseyn-bo.integration.ocp.oraclecloud.com/ic/home \
            -w %{http_code} -o response.out)
            displayName: 'Activate Integration'